name: PR Preview for Jekyll

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository  # Only run on PRs from the same repo
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build -d _site

      - name: Deploy preview to branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: pr-preview/pr-${{ github.event.pull_request.number }}

      - name: Output Preview URL
        run: echo "Preview: https://organic-no-ai.github.io/web-site/?preview=pr-${{ github.event.pull_request.number }}"
